version: "3.7"

services:
    csharp-test:
      build: 
        context: .
        dockerfile: DockerFile
      volumes:
        - ../:/app
      environment:
        - TZ=UTC
      tty: true
      env_file:
         - .env
      networks:
        - piers_dev_network
networks:
  piers_dev_network:
    external: true